# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4ab38e302f93840518cea6027445594d0aa819bd3494f98f7847d1c0c075621fe64682abfba0fa4a59cdb73d55f703ae94d8b142cab4952ecbc423902b822ee

test:
  secret_key_base: 0973efc374e8246c49da92dc6442c119a9ae69c72f33e1a807105879e506d6010060f642e584fd747d4a139736196ab759b85cd4f98ef03fd6b959a8add41fbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
